#! /usr/bin/env python
from bs4 import BeautifulSoup
import requests
import sys

system_args = sys.argv
submission_file = system_args[1]
name,extension = submission_file.split('.')

if len(system_args) > 2 :
	problem_code = system_args[2]
else:
	problem_code = name

language_codes = {
	'c++' : 41,
	'lua' : 26,
	'py' : 4,
	'pl' : 3,
	'java' : 10,
	'txt' : 62,
	'c' : 11
}

#login
f = open('auth.pass', "r")
user_name = f.readline()
password = f.readline()
f.close()
login_data = {
	'name': user_name,
	'pass': password,
	'form_id':'user_login_block'
}

s = requests.Session()
r = s.post('http://www.codechef.com/node?destination=node', data=login_data)

#submit
url = 'http://www.codechef.com/submit/' + problem_code

r = s.get(url)
soup = BeautifulSoup(r.text)
if soup.title.string == 'Access Denied | CodeChef':
	print 'login failed'
	exit(0)

if soup.title.string == 'Page not found | CodeChef':
	print 'incorrect problem id'
	exit(0)

def inputs(tag):
	required = ['form_build_id', 'form_token', 'submission_unique_id', 'title']
	return tag.get('name') in required and tag.parent.get('class')

ins = soup.find_all(inputs)
f = open(submission_file, "r")
submit_data = {
	'body' : f.read(),
	'files[program_file]' : '',
	'submission_language' : language_codes.get(extension, 41),
	'problem_code' : problem_code,
	'changed' : '',
	'form_id' : 'answer_node_form'
}
f.close()
for k in ins:
	submit_data[k['name']] = k.get('value')

r = s.post(url, data=submit_data)

soup = BeautifulSoup(r.text)

if soup.title.string == 'Submit a solution | CodeChef':
	print 'submission failed'
	exit(0)

if soup.title.string != 'CodeChef User | CodeChef':
	print 'submission failed: unexpected error'
	exit(0)

#result
print 'http://www.codechef.com/status/'+problem_code+','+user_name
